### ISSUE TITLE
Availability from maven

### ISSUE THREAD

**Issue by bobknoths** [FDMediagroep/hamcrest-jackson#1]
Hi,
You give a maven dependency in your README but it doesn't seem to be known to the repositories.
Do you have any plans to add it?  It would be much easier for us to use it if you did.

Cheers

Bob

**Comment by jmsnoeij** [comment]
Hi Bob,

Thanks for you interest in our little project. **YES** it is definitely our plan to add this to a maven repository (either the central repo or our own). Our development systems are currently running on closed servers, but we are in the process of migrating those.

For the time being, I've uploaded the most recent releases to the web so you can download them there:

```
http://files2.fd.nl/development/hamcrest-jackson/binaries/1.0.4/hamcrest-jackson-1.0.4.jar
```

Hopefully this helps you,

With regards,

Jeroen M Snoeij

**Comment by JHannema** [comment]
Hi Bob, 

We are pleased to inform you that our projects are now available on Maven Central. You can find them here: http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22nl.fd%22 

To add hamcrest-jackson to your project specifically you can add this to your pom: 

```
<dependency>
    <groupId>nl.fd</groupId>
    <artifactId>hamcrest-jackson</artifactId>
    <version>1.0.5</version>
</dependency>
```

We hope this will help you. 
Kind regards, 

Joram Hannema

**Comment by Krijger** [comment]
Whoohoo!
Way to go :D
